default:
	@echo 'Usage:'
	@echo '      make <option>'
	@echo '         <option> = i, ii, iii, or serial, corresponding to the question number'


serial:
	mpif90 -o serial hw1_serial.f90

i:
	mpif90 -o hw1_i hw1_i_SEND_RECV.f90

ii:
	mpif90 -o hw1_i hw1_ii_SENDRECV.f90

iii:
	mpif90 -o hw1_i hw1_iii_ISEND_IRECV.f09