default:
	@echo 'Usage:'
	@echo '      make <option>'
	@echo '         <option> = i, ii, iii, or serial, corresponding to the question number'


serial:
	mpif90 -o serial hw1_0_serial.f90

i:
	mpif90 -o hw1_i hw1_1_SEND_RECV.f90

ii:
	mpif90 -o hw1_i hw1_2_SENDRECV.f90

iii:
	mpif90 -o hw1_i hw1_3_ISEND_IRECV.f09